[package]
name = "rust_book"
version = "0.1.0"
authors = ["Edward Zelis <zeledvards@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10.2", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "voice", "framework", "cache", "standard_framework"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
songbird = { version = "0.1.0", features = ["builtin-queue"] }
tracing-subscriber = "0.2.15"
tracing = "0.1.22"
tracing-futures = "0.2.4"
