[package]
name = "rust_book"
version = "0.1.0"
authors = ["Edward Zelis <zeledvards@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.2.15"
tracing = "0.1.22"
tracing-futures = "0.2.4"
futures = "0.3.12"
serde_json = { version = "1" }
twilight-gateway = "0.3"
twilight-http = "0.3"
twilight-model = "0.3"
twilight-standby = "0.3"
songbird = { version = "0.1.1", default-features = false, features = ["twilight-rustls", "gateway", "driver", "stock-zlib"] }