[package]
name = "rust_book"
version = "0.1.0"
authors = ["Edward Zelis <zeledvards@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-futures = "0.2.4"
songbird = "0.1.1"
serenity = "0.10.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
yaml-rust = "0.4.5"
